=== Mangod4435/project-dasher/PJDSScheme.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"required": [],
	"properties": {
		"name": {
			"type": "string"
		},
		"music": {
			"type": "string",
			"$comment": "The files must be mp3 and paste the link(raw)"
		},
		"tempo": {
			"type": "number"
		},
		"delay": {
			"type": "number"
		},
		"notes": {
			"minLength": 1,
			"type": "array",
			"items": {
				"type": "object",
				"required": [],
				"properties": {
					"beat": {
						"type": "number",
						"$comment": "Determine where's the note will spawn in horizontal"
					},
					"y": {
						"type": "number",
						"enum": [0, 1, 2],
						"$comment": "Determine where's the note will spawn in vertical"
					},
					"species": {
						"type": "string",
						"enum": ["Norm"],
						"$comment": "This is the type for the note"
					},
					"end": {
						"type": "number",
						"$comment": "Duration of the hold(this isn't required)"
					}
				}
			}
		}
	}
}

=== Mangod4435/project-dasher/Charts/ChartTest.json
{
	"$schema": "https://raw.githubusercontent.com/Mangod4435/project-dasher/main/PJDSScheme.json",
	"name": "placeholder",
	"music": "res://Music/BIG-SHOT-DELTARUNE.mp3",
	"tempo": 140.0,
	"delay": 1.83,
	"notes": [
		{
			"beat": 5,
			"end": 3,
			"y": 2,
			"species": "Norm"
		},
		{
			"beat": 6,
			"end": 3,
			"y": 1,
			"species": "Norm"
		}
	]
}
